name: Development CI
on:
  pull_request:
    types: [closed]
    branches: ["devel"]

jobs:
  build-and-push:
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login  to GHCR
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to GHCR
      run: |
          # GHCR requires lowercase image names
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          podman build -t $IMAGE_ID:latest ${{ matrix.context }}
          podman push $IMAGE_ID:latest